name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          ./configure
          make

      - name: Test
        run: |
          ./testsuite-inline.sh ./abduco
