name: macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Test
        timeout-minutes: 2
        run: ./tests/testsuite-inline.sh ./target/release/lich
